n = str(input('Nome: ')).strip()
minuscula = n.lower()
maiscula = n.upper()
letras = len(n)-n.count(' ')
l1 = (n.find(' '))
print('Seu nome em letras minusculas é {}'.format(minuscula))
print('Seu nome em letras maisculas é {}'.format(maiscula))
print('Seu nome tem {} letras'.format(letras))
print('Seu primeiro nome tem {} letras'.format(l1))
