X = input('Escreva algo: ')
print('O tipo primitivo de {} é {}'.format(X,type(X)))
print('Só tem espaço? ',X.isspace())
print('É um número? ', X.isnumeric())
print('É alfabético? ', X.isalpha())
print('É alfanúmerico? ',X.isalnum())
print('Está em máisculas? ',X.isupper())
print('Está em minusculas? ',X.islower())
print('Está em capitalizada? ',X.istitle())
